import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";
import { Locale, locales } from "@/navigation";
import { unstable_setRequestLocale } from "next-intl/server";

import { useMessages } from "next-intl";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Bro Meets Science",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo-light.ico",
        media: "(prefers-color-scheme: light)",
      },
      {
        url: "/logo-dark.ico",
        media: "(prefers-color-scheme: dark)",
      },
    ],
  },
};

interface Props {
  children: React.ReactNode;
  params: { locale: Locale };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<Props>) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();
  return <div>{children}</div>;
}
