name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the Docker image'
        required: true
        type: string
      context:
        description: 'Build context'
        required: true
        type: string
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
        type: string
      build-args:
        description: 'Optional build arguments as a single string (e.g., "ARG1=value1 ARG2=value2")'
        required: false
        type: string
      environment:
        description: 'Environment variables to set for the build'
        required: false
        type: string
        default: ""
      pull:
        description: 'Whether to pull the base image before building'
        required: false
        type: boolean
        default: false
    secrets:
      DOCKERHUB_PASSWORD:
        description: 'Docker Hub password'
        required: true
      DOCKERHUB_USERNAME:
        description: 'Docker Hub username'
        required: true

jobs:
  docker-build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate date tag
        id: date_tag
        shell: powershell
        run: |
          $DateTag = (Get-Date -Format "yyyyMMddHHmm")
          Add-Content -Path $env:GITHUB_ENV -Value ("TAG_DATE=$DateTag")

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}
          tags: |
            ${{env.TAG_DATE}}
            latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:buildcache,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args || '' }}
          pull: ${{ inputs.pull }}