name: Cart Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/cart-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/cart-service.Dockerfile'
      - 'bmsSpring/cart-service.Dockerfile.dockerignore'
      - '.github/workflows/cart-service.yml'
jobs:
  test-template-module:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: template-module
  test-cart-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: cart-service
      local-modules: template-module
  build-and-push-cart-service:
    needs: [ test-template-module, test-cart-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: cart-service-bms
      context: ./bmsSpring
      #        dockerfile: ./bmsSpring/cart-service/Dockerfile
      dockerfile: ./bmsSpring/cart-service.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}