name: Config Server Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/config-server/**'
      - 'bmsSpring/config-server.Dockerfile'
      - 'bmsSpring/config-server.Dockerfile.dockerignore'
      - '.github/workflows/config-server.yml'
jobs:
  test-config-server:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: config-server
  build-and-push-config-server:
    needs: [ test-config-server ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: config-server-bms
      #      context: ./bmsSpring/config-server
      #      dockerfile: ./bmsSpring/config-server/Dockerfile
      context: ./bmsSpring
      dockerfile: ./bmsSpring/config-server.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}