name: Config Server Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/config-server/**'
jobs:
  test-config-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: config-service
      local-modules: template-module
  build-and-push-config-server:
    needs: [ test-config-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: config-server-bms
      context: ./bmsSpring/config-server
      dockerfile: ./bmsSpring/config-server/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}