name: Config Server

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/config-server/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: config-server-bms
      context: ./bmsSpring/config-server
      dockerfile: ./bmsSpring/config-server/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}