name: Day Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/day-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/ollama-search/**'
      - 'bmsSpring/day-service.Dockerfile'
      - 'bmsSpring/day-service.Dockerfile.dockerignore'
      - '.github/workflows/day-service.yml'
jobs:
  test-template-module:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: template-module
  test-redis-cache:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: redis-cache
  test-ollama-search:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: ollama-search
  test-day-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: day-service
      local-modules: ollama-search,redis-cache,template-module
  build-and-push-day-service:
    needs: [ test-template-module, test-redis-cache, test-ollama-search, test-day-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: day-service-bms
      context: ./bmsSpring
      #      dockerfile: ./bmsSpring/day-service/Dockerfile
      dockerfile: ./bmsSpring/day-service.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}