name: Test Docker Login

on:
  workflow_dispatch: { }
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      image-name: config-server-bms
      context: ./bmsSpring/config-server
      dockerfile: ./bmsSpring/config-server/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}