name: Test Docker Login

on:
  workflow_dispatch: { }
jobs:
  docker-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Verify Docker Login Success
        run: |
          if docker info > /dev/null 2>&1; then
            echo "Docker login succeeded."
          else
            echo "Docker login failed."
            exit 1
          fi