name: Gateway Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/gateway-service/**'
jobs:
  build-and-push-gateway-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: gateway-service-bms
      context: ./bmsSpring/gateway-service
      dockerfile: ./bmsSpring/gateway-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}