name: Gateway Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/gateway-service/**'
      - 'bmsSpring/gateway-service.Dockerfile'
      - 'bmsSpring/gateway-service.Dockerfile.dockerignore'
      - '.github/workflows/gateway-service.yml'
jobs:
  test-gateway-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: gateway-service
  build-and-push-gateway-service:
    needs: [ test-gateway-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: gateway-service-bms
        #      context: ./bmsSpring/gateway-service
      #      dockerfile: ./bmsSpring/gateway-service/Dockerfile
      context: ./bmsSpring
      dockerfile: ./bmsSpring/gateway-service.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}