name: Kanban Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/kanban-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
jobs:
  build-and-push-kanban-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: kanban-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/kanban-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}