name: Kanban Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/kanban-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/kanban-service.Dockerfile'
      - 'bmsSpring/kanban-service.Dockerfile.dockerignore'
      - '.github/workflows/kanban-service.yml'
jobs:
  test-template-module:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: template-module
  test-redis-cache:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: redis-cache
  test-kanban-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: kanban-service
      local-modules: redis-cache,template-module
  build-and-push-kanban-service:
    needs: [ test-template-module, test-redis-cache, test-kanban-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: kanban-service-bms
      context: ./bmsSpring
      #      dockerfile: ./bmsSpring/kanban-service/Dockerfile
      dockerfile: ./bmsSpring/kanban-service.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}