name: Next Static Server Docker Image
on:
  workflow_dispatch: { }
  workflow_call: { }
#  push:
#    branches:
#      - main
#    paths:
#      - 'client-next/**'
#      - 'bmsSpring/next-static-server/**'
jobs:
  test-next-static-server:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: next-static-server
  build-and-push-next-static-server:
    needs: [ test-next-static-server ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: next-static-server-bms
      context: ./bmsSpring/next-static-server
      dockerfile: ./bmsSpring/next-static-server/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}