name: NextJS Build Controller
on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'client-next/**'
      - 'bmsSpring/next-static-server/**'


jobs:
  build-and-push-nextjs:
    uses: ./.github/workflows/next-js.yml
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  build-and-push-next-static-server:
    needs: build-and-push-nextjs
    uses: ./.github/workflows/next-static-server.yml
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

