name: NextJS Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'client-next/**'
jobs:
  build-and-push-next-js:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: next-js-bms
      context: ./client-next
      dockerfile: ./client-next/Dockerfile
      build-args: |
        NEXT_PUBLIC_SPRING=${{vars.NEXT_PUBLIC_SPRING}}
        NEXT_PUBLIC_SPRING_CLIENT=${{vars.NEXT_PUBLIC_SPRING_CLIENT}}
        NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET=${{vars.NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET}}
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#jobs:
#  docker-build-and-push-next-js:
#    runs-on: self-hosted
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Generate date tag
#        id: date_tag
#        shell: powershell
#        run: |
#          $DateTag = (Get-Date -Format "yyyyMMddHHmm")
#          Add-Content -Path $env:GITHUB_ENV -Value ("TAG_DATE=$DateTag")
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ secrets.DOCKERHUB_USERNAME }}/next-js-bms
#          tags: |
#            ${{env.TAG_DATE}}
#            latest
#
#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v6
#        with:
#          context: ./client-next
#          file: ./client-next/Dockerfile
#          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/next-js-bms:buildcache
#          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/next-js-bms:buildcache,mode=max
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          build-args: |
#            NEXT_PUBLIC_SPRING=${{vars.NEXT_PUBLIC_SPRING}}
#            NEXT_PUBLIC_SPRING_CLIENT=${{vars.NEXT_PUBLIC_SPRING_CLIENT}}
#            NEXTAUTH_URL=${{vars.NEXTAUTH_URL}}
#            NEXTAUTH_URL_INTERNAL=${{vars.NEXTAUTH_URL_INTERNAL}}
#            NODE_TLS_REJECT_UNAUTHORIZED=${{vars.NODE_TLS_REJECT_UNAUTHORIZED}}
#            GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
#            GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
#            GITHUB_CLIENT_SECRET=${{secrets.GITHUBS_CLIENT_SECRET}}
#            GITHUB_CLIENT_ID=${{secrets.GITHUBS_CLIENT_ID}}
#            NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}
#            OLLAMA_MODEL=${{vars.OLLAMA_MODEL}}
#            OLLAMA_BASE_URL=${{vars.OLLAMA_BASE_URL}}
#            OLLAMA_EMBEDDING=${{vars.OLLAMA_EMBEDDING}}
#            POSTGRES_HOST=${{vars.POSTGRES_HOST}}
#            POSTGRES_PORT=${{vars.POSTGRES_PORT}}
#            POSTGRES_USER=${{secrets.POSTGRES_USER}}
#            POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
#            POSTGRES_DB=${{vars.POSTGRES_DB}}
#            NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET=${{vars.NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET}}
#            OLLAMA_TEMPERATURE=${{vars.OLLAMA_TEMPERATURE}}
#            OLLAMA_CHAT_COUNT=${{vars.OLLAMA_CHAT_COUNT}}
#            NEXT_ZIPKIN_URL=${{vars.NEXT_ZIPKIN_URL}}
#            NEXT_SERVICE_NAME=${{vars.NEXT_SERVICE_NAME}}
#            NEXT_OTEL_VERBOSE=${{vars.NEXT_OTEL_VERBOSE}}
#            NEXT_TRACING_PROBABILITY=${{vars.NEXT_TRACING_PROBABILITY}}
