name: NextJS Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'client-next/**'
jobs:
  build-and-push:
    uses: ./.github/workflow-templates/build-and-push.yml
    with:
      image-name: next-js-bms
      context: ./client-next
      dockerfile: ./client-next/Dockerfile
      build-args: |
        NEXT_PUBLIC_SPRING=${{env.NEXT_PUBLIC_SPRING}}
        NEXT_PUBLIC_SPRING_CLIENT=${{env.NEXT_PUBLIC_SPRING_CLIENT}}
        NEXTAUTH_URL=${{env.NEXTAUTH_URL}}
        NEXTAUTH_URL_INTERNAL=${{env.NEXTAUTH_URL_INTERNAL}}
        NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}
        NODE_TLS_REJECT_UNAUTHORIZED=${{env.NODE_TLS_REJECT_UNAUTHORIZED}}
        GOOGLE_CLIENT_SECRET=${{secrets.GOOGLE_CLIENT_SECRET}}
        GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}}
        GITHUB_CLIENT_SECRET=${{secrets.GITHUBS_CLIENT_SECRET}}
        GITHUB_CLIENT_ID=${{secrets.GITHUBS_CLIENT_ID}}
        OLLAMA_MODEL=${{env.OLLAMA_MODEL}}
        OLLAMA_BASE_URL=${{env.OLLAMA_BASE_URL}}
        OLLAMA_EMBEDDING=${{env.OLLAMA_EMBEDDING}}
        POSTGRES_HOST=${{env.POSTGRES_HOST}}
        POSTGRES_PORT=${{env.POSTGRES_PORT}}
        POSTGRES_USER=${{secrets.POSTGRES_USER}}
        POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB=${{env.POSTGRES_DB}}
        NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET=${{env.NEXT_PUBLIC_SPRING_CLIENT_WEBSOCKET}}
        OLLAMA_TEMPERATURE=${{env.OLLAMA_TEMPERATURE}}
        OLLAMA_CHAT_COUNT=${{env.OLLAMA_CHAT_COUNT}}
        NEXT_ZIPKIN_URL=${{env.NEXT_ZIPKIN_URL}}
        NEXT_SERVICE_NAME=${{env.NEXT_SERVICE_NAME}}
        NEXT_OTEL_VERBOSE=${{env.NEXT_OTEL_VERBOSE}}
        NEXT_TRACING_PROBABILITY=${{env.NEXT_TRACING_PROBABILITY}}
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

