name: Post Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/post-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/ollama-search/**'
jobs:
  test-template-module:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: template-module
  test-redis-cache:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: redis-cache
  test-ollama-search:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: ollama-search
  test-post-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: post-service
      local-modules: ollama-search,redis-cache,template-module
  build-and-push-post-service:
    needs: [ test-template-module, test-redis-cache, test-ollama-search, test-post-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: post-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/post-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}