name: Post Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/post-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/ollama-search/**'
jobs:
  build-and-push-post-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: post-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/post-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}