name: Pre Build Docker Image
on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the Docker image'
        required: true
        type: string
      context:
        description: 'Build context'
        required: true
        type: string
      dockerfile:
        description: 'Path to Dockerfile'
        required: true
        type: string
      environment:
        description: 'Environment variables to set for the build'
        required: false
        type: string
        default: ""
    secrets:
      DOCKERHUB_PASSWORD:
        description: 'Docker Hub password'
        required: true
      DOCKERHUB_USERNAME:
        description: 'Docker Hub username'
        required: true
jobs:
  pre-build:
    runs-on: self-hosted
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate date tag
        id: date_tag
        shell: powershell
        run: |
          $DateTag = (Get-Date -Format "yyyyMMddHHmm")
          Add-Content -Path $env:GITHUB_ENV -Value ("TAG_DATE=$DateTag")

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}
          tags: |
            ${{env.TAG_DATE}}
            latest
