name: Recipe Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/recipe-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/ollama-search/**'
jobs:
  build-and-push-recipe-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: recipe-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/recipe-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}