name: Service Registry

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/service-registry/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: service-registry-bms
      context: ./bmsSpring/service-registry
      dockerfile: ./bmsSpring/service-registry/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}