name: Service Registry Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/service-registry/**'
      - 'bmsSpring/service-registry.Dockerfile'
      - 'bmsSpring/service-registry.Dockerfile.dockerignore'
      - 'bmsSpring/base-docker/independent-build.Dockerfile'
      - 'bmsSpring/base-docker/independent-deps.Dockerfile'
      - 'bmsSpring/base-docker/runtime.Dockerfile'
      - 'bmsSpring/pom.xml'
      - '.github/workflows/service-registry.yml'
jobs:
  test-service-registry:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: service-registry
  build-and-push-service-registry:
    needs: [ test-service-registry ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: service-registry-bms
      #      context: ./bmsSpring/service-registry
      #      dockerfile: ./bmsSpring/service-registry/Dockerfile
      context: ./bmsSpring
      dockerfile: ./bmsSpring/service-registry.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}