name: Test Spring App

on:
  workflow_call:
    inputs:
      app-path:
        description: 'Path to the Spring application'
        required: true
        type: string
      local-modules:
        description: 'Comma-separated list of local modules to install first'
        required: false
        type: string

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '22'

      - name: Ensure Maven is installed
        run: mvn --version
      - name: Check Docker version
        run: docker --version
      - name: Install Modules
        if: ${{ inputs.local-modules != '' }}
        shell: powershell
        run: |
          $modules = "${{ inputs.local-modules }}".Split(',')
          foreach ($module in $modules) {
                  Write-Host "Installing $module..."
                  Push-Location "bmsSpring/$module"
                  mvn install -DskipTests
                  Pop-Location
          }
      - name: Run Service Tests
        run: |
          cd bmsSpring/${{ inputs.app-path }}
          mvn clean test 
