name: Test Spring App

on:
  push:
    paths:
      - 'bmsSpring/redis-cache/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 22
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '22'

      - name: Ensure Maven is installed
        run: mvn --version
      - name: Check Docker version
        run: docker --version

      - name: Run Service Tests
        run: |
          cd bmsSpring/redis-cache
          mvn clean test --enable-preview
