name: Toxic Prediction Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsFlask/toxicPrediction/**'
      - 'bmsFlask/toxic-prediction.Dockerfile'
      - 'bmsFlask/toxic-prediction.Dockerfile.dockerignore'
      - 'bmsFlask/base-docker/build.Dockerfile'
      - '.github/workflows/toxic-prediction-service.yml'
jobs:
  build-and-push-toxic-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: toxic-prediction-service-bms
      context: ./bmsFlask
      dockerfile: ./bmsFlask/toxic-prediction.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}