name: User Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/user-service/**'
      - 'bmsSpring/template-module/**'
      - 'bmsSpring/redis-cache/**'
      - 'bmsSpring/ollama-search/**'
      - 'bmsSpring/user-service.Dockerfile'
      - 'bmsSpring/user-service.Dockerfile.dockerignore'
      - 'bmsSpring/base-docker/template-module.Dockerfile'
      - 'bmsSpring/base-docker/redis-module.Dockerfile'
      - 'bmsSpring/base-docker/ollama-module.Dockerfile'
      - 'bmsSpring/base-docker/parent-module.Dockerfile'
      - 'bmsSpring/base-docker/with-tro-builder.Dockerfile'
      - 'bmsSpring/base-docker/runtime.Dockerfile'
      - 'bmsSpring/pom.xml'
      - '.github/workflows/user-service.yml'
jobs:
  test-template-module:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: template-module
  test-redis-cache:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: redis-cache
  test-ollama-search:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: ollama-search
  test-user-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: user-service
      local-modules: ollama-search,redis-cache,template-module
  build-and-push-user-service:
    needs: [ test-template-module, test-redis-cache, test-ollama-search, test-user-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: user-service-bms
      context: ./bmsSpring
      #      dockerfile: ./bmsSpring/user-service/Dockerfile
      dockerfile: ./bmsSpring/user-service.Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}