name: User Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/user-service/**'
      - 'bmsSpring/template-module/**'
jobs:
  build-and-push-user-service:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: user-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/user-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}