name: User Service

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/user-service/**'
jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      image-name: user-service-bms
      context: ./bmsSpring
      dockerfile: ./bmsSpring/user-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}