name: Websocket Service Docker Image

on:
  workflow_dispatch: { }
  push:
    branches:
      - main
    paths:
      - 'bmsSpring/websocket-service/**'
jobs:
  test-websocket-service:
    uses: ./.github/workflows/test-run.yml
    with:
      app-path: websocket-service
  build-and-push-websocket-service:
    needs: [ test-websocket-service ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: websocket-service-bms
      context: ./bmsSpring/websocket-service
      dockerfile: ./bmsSpring/websocket-service/Dockerfile
    secrets:
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}